### ISSUE TITLE
Dosen't work...

### ISSUE THREAD

**Issue by ghost** [dtinth/i2DX#3]
If i open a text doc and mash buttons it does type something, but when i try and use it with the actual game it doesn't work...

**Comment by dtinth** [comment]
Hello, which games have you tried? On which operating system?

**Comment by ghost** [comment]
beatmania and beatmania 2nd mix (using mame). Also tried pop'n music 19, that didn't work either.
OS is windows 10.

**Comment by ghost** [comment]
hello...still not working...

**Comment by dtinth** [comment]
Hi, sorry I forgot to reply. I am afraid that MAME uses a different mechanism to receive input than what i2DX uses to produce keypresses.

I recommend using this with modern BMS players instead.

https://bms.neocities.org/

**Comment by ghost** [comment]
oh...ok...thx anyway :(
guess i just have to keep playing with my keyboard...
