### ISSUE TITLE
taiko mode "key map not found for taiko_XX"

### ISSUE THREAD

**Issue by ghost** [dtinth/i2DX#6]
so i found some games that work with this thing (yay). iidx and pop'n work fine (haven't tried jubeat yet) but when i try to use the taiko mode it keeps giving me errors. It loads fine when i actually tap the drum the server program says "key map not found for taiko_XX, player 1" (The XX is the part of the drum i tried to hit,  a1, a2, b1, etc.) not really sure why it does this.

**Comment by dtinth** [comment]
There is no default keymap for Taiko mode right now, but you can fix this by opening "config.ini" in the server folder and added the required keymaps. :)

After modifying the config file, please restart the i2DX server and try again.

**Comment by ghost** [comment]
how do i do that?

**Comment by dtinth** [comment]
In the "server" folder you should find a file called "config.ini". You can try editing that file with Notepad.

**Comment by ghost** [comment]
i tried adding the config, pressing the left rim or left center still gives me the key map error, pressing right center disconnects me (and also causes the server to refuse any more connections until i relaunch it,). haven't tested right rim.

error message the server gives me after disconnecting me:
ERROR:tornado.application:Uncaught exception in /ws
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\tornado-5.0.2-py2.7-win32.egg\tornado\websocket.py", line 498, in _run_callback
    result = callback(*args, **kwargs)
  File "C:\Users\fungu\Downloads\i2DX-master\server\libi2dx.py", line 41, in on_message
    self.toggle_key(parts[1], True, parts[2])
  File "C:\Users\fungu\Downloads\i2DX-master\server\server-windows-autopy.py", line 10, in toggle_key
    key.toggle(libi2dx.config.get('keymap_player%s' % player, key_id), state)
TypeError: argument must be char, not str
connection closed

**Comment by dtinth** [comment]
Can you paste your config file here? Thanks!

**Comment by WhyEvenBother** [comment]
just add this in the config.ini between the jubeat keymaps and start/select keymaps, e and i are the rim controls and r and u is the center controls.:
taiko_b1 = e
taiko_a1 = r
taiko_a2 = u
taiko_b2 = i

**Comment by ghost** [comment]
config file: 
[config.zip](https://github.com/dtinth/i2DX/files/2014766/config.zip)

It's zipped because github wouldn't take the ini format.

**Comment by WhyEvenBother** [comment]
[config.zip](https://github.com/dtinth/i2DX/files/2015955/config.zip)
Here i fixed it.

**Comment by ghost** [comment]
alright, i'll try it out.

**Comment by ghost** [comment]
@WhyEvenBother 
yay it works :D
thx

**Comment by WhyEvenBother** [comment]
You're Welcome!
