### ISSUE TITLE
Safari can't connect

### ISSUE THREAD

**Issue by TaroSykes** [dtinth/i2DX#7]
Hi there, Safari's throwing a "could not connect to server" error at me. Any fixes?

**Comment by TaroSykes** [comment]
There's also no launcher - and Opera doesn't work either.

**Comment by TaroSykes** [comment]
I can connect on my PC, just not anywhere else.

**Comment by FunkyEgg** [comment]
did you ever fix the issue

**Comment by TaroSykes** [comment]
nope, this isn't maintained any longer so it's kinda useless
